name: Fetch from Planning Center API

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install node-fetch@3

      - name: Run fetch script
        env:
          PCO_CLIENT_ID: ${{ secrets.PCO_CLIENT_ID }}
          PCO_CLIENT_SECRET: ${{ secrets.PCO_CLIENT_SECRET }}
          PCO_CAMPAIGN_ID: ${{ secrets.PCO_CAMPAIGN_ID }}
        run: node scripts/fetch.js

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json [skip ci]" || echo "No changes"
          git push

